services:
  postgres:
    image: postgres:latest
    container_name: wallet-postgres
    environment:
      POSTGRES_DB: wallet_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: wallet-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: wallet
      RABBITMQ_DEFAULT_PASS: wallet123
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf