spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

TWILIO-account-sid=${TWILIO-account-sid}
TWILIO-auth-token=${TWILIO-auth-token}
TWILIO-verify-service-sid=${TWILIO-verify-service-sid}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration