CREATE TABLE wallets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL ,
    balance DECIMAL NOT NULL ,
    currency VARCHAR(255) NOT NULL ,
    status VARCHAR(255) NOT NULL ,
    version INT NOT NULL ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wallets_user
                     FOREIGN KEY (user_id)
                     REFERENCES users(id)
);