CREATE TABLE transactions(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_wallet_id INT NOT NULL ,
    to_wallet_id INT NOT NULL ,
    amount DECIMAL(15,2) NOT NULL ,
    types VARCHAR(255) NOT NULL ,
    status VARCHAR(255) NOT NULL ,
    ref_no INT NOT NULL ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transactions_from_wallet
                         foreign key (from_wallet_id)
                         references wallets(id),

    CONSTRAINT fk_transactions_to_wallet
                         foreign key (to_wallet_id)
                         references wallets(id)
);