CREATE TABLE idempotency_keys(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL ,
    key VARCHAR(255) NOT NULL ,
    request_hash VARCHAR(255) NOT NULL ,
    transaction_id INT NOT NULL ,
    status VARCHAR(255) NOT NULL ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_idempotency_keys_user
                             FOREIGN KEY (user_id)
                             REFERENCES users(id),

    CONSTRAINT fk_idempotency_keys_transaction
                             FOREIGN KEY (transaction_id)
                             REFERENCES transactions(id)
);