CREATE TABLE ledger_entries(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id INT NOT NULL ,
    wallet_id INT NOT NULL ,
    types VARCHAR(255) NOT NULL ,
    amount DECIMAL(15,2) NOT NULL ,
    balance_after DECIMAL(15,2) NOT NULL ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ledger_entries_transaction
                           FOREIGN KEY (transaction_id)
                           REFERENCES transactions(id),

    CONSTRAINT fk_ledger_entries_wallet
                           FOREIGN KEY (wallet_id)
                           REFERENCES wallets(id)
);