CREATE TABLE outbox_events(
     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key_id INT NOT NULL ,
    event_type VARCHAR(255) NOT NULL ,
    payload VARCHAR(255) NOT NULL ,
    status VARCHAR(255) NOT NULL ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_outbox_events_idempotency_key
                          FOREIGN KEY (idempotency_key_id)
                          REFERENCES idempotency_keys(id)
);